### ISSUE TITLE
Удаление стикеров от юзеров

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#10]
Опциональная фича. Бот по тихому вырезает стикеры от юзеров и запрещает на уровне телеграма присылать стикеры конкретному юзеру.

**Comment by sergeysova** [comment]
Наверняка @syabro хочет эту фичу

**Comment by dmitryshelomanov** [comment]
@sergeysova не понял смысла фичи. Это что запрет на стикеры ? или как ? сложна D

**Comment by syabro** [comment]
@userbq201 да

**Comment by dmitryshelomanov** [comment]
@syabro типа отправил стикер, а бот мб ответ сделает и предупреждение. Как в чате реакта

**Comment by syabro** [comment]
@userbq201 это заебывает
просто чистить сразу и все

**Comment by sergeysova** [comment]
@userbq201 бот просто будет сразу же удалять стикеры

**Comment by dmitryshelomanov** [comment]
@sergeysova я с тестами пока не смог. Я возьму стикеры удаление. Нужно просто удалять сообщение если это стикер ? Или в бд заносить тоже ? что бы просчитать сколько раз он стикер отправил. И тогда можно после удаление допустим ответить что то. В стиле заебал стикерами и тд. Ну нормальные реплики ток придумать

**Comment by dmitryshelomanov** [comment]
@sergeysova ага. А смысл. Если все вносится в таблицу messages. Мб ее  модернизировать ? И сделать что то типа поля type ? И вносить **text** если это текст или **stiker** если это стикер. И тут просчитать можно сколько раз стикер отправил тот чел

**Comment by dmitryshelomanov** [comment]
@sergeysova на счет опционально? Это в рантайме врубить и вырубить ?
как на счет команды` !option:name:disable[enable]`

**Comment by syabro** [comment]
@userbq201 зачем в бд? если стикеров не будет в канале - какая разница сколько раз кто отправил и как заебал? )

**Comment by dmitryshelomanov** [comment]
@syabro тогда зачем это issue ? Если можно стикеры отрубить

**Comment by sergeysova** [comment]
@userbq201 стикеры не надо хранить в базе. Для начала делаем самый простой вариант:
У каждого чата должны быть настройки в базе (в любом виде). И из лички можно настроить каждый чат (кто это может?).

Вообще слишком много вопросов надо решить перед тем как запилить эту фичу.

**Comment by sergeysova** [comment]
@userbq201 нельзя отрубить стикеры всем сразу. Можно только по одному.

**Comment by sergeysova** [comment]
Обновил описание

**Comment by syabro** [comment]
> Можно только по одному. 

Угу. Поэтому самый просто варинт просто тереть без сохранений и прочего говна

**Comment by dmitryshelomanov** [comment]
@sergeysova @syabro на счет опционально ? что там

**Comment by dmitryshelomanov** [comment]
@sergeysova из лички это как ? Как будет окончательный варик ? В бд можно состояние, а в рантайме менять. Пробросив состояние в контекст

**Comment by dmitryshelomanov** [comment]
удаление изи. Контекст изи. Там траблы с регуляркой. Бд еще нужно для правил чата. Блин я чуть занят (. Или позже или завтра D. Получается фактически создать бд для конфига чата если таковой нету. Это начальный стейт. И методы которые в рантайме меняют стейт ?

**Comment by sergeysova** [comment]
Выполнено в #41
