### ISSUE TITLE
Общий список админов для всех групп

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#11]
Вести в базе список админов.

Менеджмент cписка, один из:
- обновлять исходя из существующих админов всех групп (обновлять периодически и/или по event, плюс ручное обновление) 
- поддерживать список полностью руками 

При входе в чат пользователя из списка админов, давать ему права админа автоматически.

В случае удаления юзера из админлиста, убивать его во всех группах.

В случае бана юзера:
- ✅ не реагировать (админы под защитой)
- банить и удалять из спамлиста (админы подвержены)

**Comment by sergeysova** [comment]
@Fl0pZz на сервере будет тяжело поддерживать оба варианта.
Нужно будет вести 2 списка, и мержить их. Один который юзеры составляют сами, другой автоматический. Причем если люди уберут админа из кастомного списка, то возможно захотят добавить его в блэклист админов. 

Идея первого варианта такая: если админа добавили хоть в один чат, то он становится админом во всех чатах (с одинаковыми правами).

**Comment by sergeysova** [comment]
Необходимо решить проблему злостных бандебилов.


#### Кейс:
1. Левый чувак создает группу
2. Добавляет в неё бота. Бот считает его всея админом
3. Чувак добавляет жертву в новую группу
4. Вызывает команду "Спам" на сообщении юзверя о прибытии (или если он что напишет, или по юзернейму)
5. Юзер забанен во всех чатах как спамер
6. Об этом админы узнают не сразу (из приватного канала логов)

#### Возможное решение
> Варианты описаны ниже, ставьте 👍 за подходящий

**Comment by sergeysova** [comment]
### 1.

Вести ручной список админов (необходимо иметь root-админа).

И рут админ добавляет в список юзеров в личке с ботом (или ещё как).

Минусы: 
- Неудобно
- Если появился админ-дебил, выкинуть его будет сложно, если рутовый админ сдох или в оффлайне

Плюсы:
- Полный контроль над списком админов
- Админы могут модерировать даже в тех чатах, где сами не находятся в списке админов

**Comment by sergeysova** [comment]
### 2.

Вести ручной список групп в которых бот может орудовать и на основании этого списка составлять общий список админов.

При добавлении в группы бот игнорит происходящее в них до тех пор, пока группы нет в его внутреннем списке одобренных. Группу нужно будет добавлять руками. Это может делать рут админ или же любой админ в личке с ботом. 

Минусы:
- Не удобно
- Если в отдельной группе появился админ-дебил, то отхватит всё сообщество/группа и придется удалять админа из самой группы, что не всегда возможно быстро

Плюсы:
- Полный контроль над списком групп
- Нет проблемы рутового админа ибо автор группы или админ-приглашатель смогут кикнуть админа-дебила

**Comment by sergeysova** [comment]
### 3.

Отслеживать кто добавил бота. Если админ из общего списка, то добавлять группу в базу и забирать список админов. Ежели нет. То игнорить сообщения из этой группы.

Минусы:
- Если бота добавили в группу случайно (маловероятно, но все же) или целенаправленно, то в общий список войдут админы из этой группы
- Нужен черный список админов/групп

Плюсы:
- Нет ручного управления

**Comment by Fl0pZz** [comment]
Дополнение к первому варианту - можно сделать общий чат для админов, все участники которого автоматически заносятся в списко админов

**Comment by sergeysova** [comment]
@Fl0pZz а можно брать юзеров/админов приватного канала логов для админов.

**Comment by vkurchatkin** [comment]
Я не понял, идея в том чтобы на все чаты был единый список админов?

**Comment by sergeysova** [comment]
@vkurchatkin примерно да, но этот список может быть также чисто внутренним.

Также имеется проблема добавления бота в произвольные группы. Причина: бан за спам, банит во всех группах сразу

**Comment by Fl0pZz** [comment]
Да, и при входе из одно чата в другой права автоматически давались,а если было принято решение об исключении, то это тоже бы делалось автоматом

**Comment by sergeysova** [comment]
@Fl0pZz 
> при входе из одно чата в другой права автоматически давались

я бы не надеялся, что многие дадут боту права на добавление админов

**Comment by Fl0pZz** [comment]
@sergeysova предлагаю закрыть issue за неактуальностью
