### ISSUE TITLE
Выдавать вечный RO юзерам с пустым именем

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#17]
Надо как-то резолвить их.
Функция должна быть опциональной.

@syabro там же какой-то символ?

**Comment by nordluf** [comment]
Я против. Это вахтерство и не иимеет смысла. Запрещать потому что я могу запрещать

**Comment by sergeysova** [comment]
@nordluf вообще это уже много раз в чате админов обсуждалось.

**Comment by sergeysova** [comment]
Общаться с людьми без имени крайне неудобно. Да и в некоторых клиентах верстка расползается.

**Comment by sergeysova** [comment]
К тому же в некоторых чатах и так выдают РО за пустой ник, руками.

**Comment by syabro** [comment]
@sergeysova может лучше будем в личку писать почему не стоит пустое имя юзать?

**Comment by sergeysova** [comment]
@syabro руками?

**Comment by syabro** [comment]
да
таких людей не так много чтобы тратить время на написание кода для них

**Comment by atassis** [comment]
Неактуально
