### ISSUE TITLE
Интерфейс "Бан пользователя"

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#2]
При ответе на сообщение пользователя и сообщении `!бан [причина]` происходит блокировка пользователя в чате, где была вызвана команда. При этом в базе данных создается отметка, где указывается `КЕМ`, `КОГО`, `ПРИЧИНА` и `СООБЩЕНИЕ` за которое пользователь был добавлен в черный список, так же эта информация публикуется в закрытом канале для модераторов, чтобы по просьбе данного пользователя можно было бы понимать, стоит ли разблокировать данного пользователя.

**Comment by sergeysova** [comment]
В приватный канал нужно пересылать сообщение, по которому прилетел бан. Будет проще идентифицировать нарушителя

**Comment by syabro** [comment]
Формат команды `/ban <reason>` и `!бан <reason>`

**Comment by Fl0pZz** [comment]
формат команд вида `/command` для чатов даже не думайте реализовывать, по той причине, что вы начнуть тыкать в эту команду и спамить этими сообщениями

**Comment by syabro** [comment]
@Fl0pZz бот должен сразу прибивать команду посланную ему в любом случае
В итоге я бы сделал `!spam`, `!спам` и `/spam`. Последнюю можно выпилить если будут проблемы.
Кстати регулярным юзерам тоже надо дать возможность юзать `spam` только вместо бана пусть уходит нотификация админам

**Comment by sergeysova** [comment]
@syabro как подсчитывать регулярных юзеров?

**Comment by syabro** [comment]
```js
const regularUser = !isUserAdmin
```
:)

**Comment by dmitryshelomanov** [comment]
@sergeysova **!бан** совсем нету ? а может **!бан:время в часах** м?

**Comment by sergeysova** [comment]
@userbq201 в стандартном функционале телеграма есть выдача бана на время, а также выдача readonly, также на время

**Comment by dmitryshelomanov** [comment]
@sergeysova тогда нет смысла ? Как стандартным функционалом пользоваться ?

**Comment by sergeysova** [comment]
@userbq201 на разных системах по разному

https://telegram.org/blog/admin-revolution

**Comment by dmitryshelomanov** [comment]
@sergeysova бан на время или РО это будет делать бот по какой то команде ? Типа `!RO ` и бан ?

**Comment by sergeysova** [comment]
@userbq201 бот не будет делать этого вообще.

**Comment by sergeysova** [comment]
Надо информацию о бане кидать в эластик тоже

**Comment by Fl0pZz** [comment]
вообще-то вы бота делаете, поэтому бан на время можете и у себя реализовать, тем более что список забаненых у вас есть

**Comment by sergeysova** [comment]
@Fl0pZz зачем реализовывать команду которая есть в стандартной поставке?

для удобства разве что

**Comment by Fl0pZz** [comment]
Для ведения логов.
Потребность в этой команде и команде разбана пользователей уже назревает, предлагаю дать этой issue повышенный приоритет

**Comment by sergeysova** [comment]
Реализовано
