### ISSUE TITLE
Интерфейс "Спам"

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#3]
При постулении команды `!cпам [?пользователь]` (или при ответе на сообщение) данный пользователь заносится в черные списки всех подконтрольных чатов. Его сообщения за последние 48/10/5 часов (?) удаляются со всех чатов, так же удаляется и сообщение модератора. Информация заносится в приватный канал.

Пункты для обсуждения:

- Является ли бан безаппеляционным?
- Если нет, то в течении какого срока нельзя обжаловать данное действие?
- Что, если пользователь был ошибочно помечен как спамер?
- Определить параметры очереди на удаление сообщений

**Comment by sergeysova** [comment]
Я думаю разбанить может любой модератор. Как пример: случайный бан. Было бы неплохо сохранять причину разбана.

**Comment by syabro** [comment]
Думаю формат `/spam [%reason%]` ок

**Comment by sergeysova** [comment]
@syabro формат `спам [%reason]` предложил @Fl0pZz ради более удобного бана. Ну там переключаться по 2 раза неудобно.

Я думаю нужно поддерживать оба варианта

**Comment by syabro** [comment]
Тогда `!спам`. Префикс необходим чтобы исключить вероятность случайного срабатывания

**Comment by dmitryshelomanov** [comment]
@sergeysova  месаги не удаляются. Или это не написано ?

**Comment by dmitryshelomanov** [comment]
@sergeysova 

- Что, если пользователь был ошибочно помечен как спамер?

просто удалять через минуту. Ток нужна очередь какая то. Есть готовые решения ?

**Comment by syabro** [comment]
>   просто удалять через минуту. Ток нужна очередь какая то. Есть готовые решения ?

Как это реализовать с точки зрения ux? Команда боту или веб-интерфейс?

**Comment by sergeysova** [comment]
@userbq201 
> просто удалять через минуту.

что ты имеешь ввиду? откуда и что удалять?

**Comment by sergeysova** [comment]
Надо протестить.

**Comment by dmitryshelomanov** [comment]
@sergeysova @syabro 
я имею ввиду отложенный бан на минуту или меньше. Типа случайный бан выдал и гг. 
или же выдал бан и сделать разбан. Но вот сообщения то удалятся. и че делать ? и тут гг
а вот отложенный бан с каким то интервалом. Просто очерередь туда ложим бананы и в течении 30 сек он выдается. И если не тому за 30 сек успеешь отменить и банана не будет
уловили суть ?

**Comment by sergeysova** [comment]
@userbq201 deferred ban?

Интересная фича.
Можно добавить в приватном канале кнопку `[ Разбанить ]`, пока что

**Comment by sergeysova** [comment]
Нужно еще удалять само сообщение !спам

**Comment by sergeysova** [comment]
#39
