### ISSUE TITLE
Команда !статус

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#52]
При отправке в:
- ЛС — игнор
- обслуживаемый чат — отвечает подтверждением (удаляет сообщение с командой)
- необслуживаемый чат — игнор

**Comment by Fl0pZz** [comment]
что делает это команда то? проверяет, модерируется ли чат ботом?

**Comment by sergeysova** [comment]
Да.
Нужно для людей, которые добавили боту в чат, но я ещё не добавил чат в бота
