### ISSUE TITLE
Приватный канал для модераторов

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#6]
Часто к модераторам обращаются пользователи с просьбой разбанить пользователя в каких-либо чатах. Появляется вопрос — за что пользователь был забанен? Отдельный канал позволил бы осуществлять быстрый поиск информации для принятия решения о снятии блокировки с пользователя.

Информация в канале может вестись в следующей форме:

```
@username забанен [за ?причина] модератором @username в @chat <data>

<сообщение, за которое пользователь получил бан>
```

**Comment by sergeysova** [comment]
Причем сообщение надо пересылать

**Comment by syabro** [comment]
В дальнешем конечно лучше сделать какой-то веб-интерфейс #15

**Comment by sergeysova** [comment]
@syabro зачем веб-интерфейс?

Чтобы как-то взаимодействовать со списками (бан, чс каналов, ...) ?

**Comment by syabro** [comment]
@LestaD поиск в телеге стремный
отфилтровать по юзернейму было бы удобно, хотя это можно и через бота сделать. Например `/log @syabro`

**Comment by sergeysova** [comment]
@syabro а если вместо веб интерфейса будет кибана или очень простая страничка с выборкой из эластика?

**Comment by sergeysova** [comment]
Пока что реализован самый простой вариант: все логи скидываются в канал как есть. Бан при reply на сообщение ещё и отправляет сообщение в приватный канал
