### ISSUE TITLE
Реакция бота на нового юзера

### ISSUE THREAD

**Issue by sergeysova** [telegram-ru/ru-bot#7]
При входе юзера в чат проверять его наличие в черном списке.

Если он там есть, сразу же банить и удалять его сообщения, если есть

**Comment by dmitryshelomanov** [comment]
Вроде сделал. Залью позже. хз как. Не просто же комитить. cz нету ? А и я не уверен работает ли удаление месаг.

**Comment by sergeysova** [comment]
Надо протестить эту фичу и #3

**Comment by dmitryshelomanov** [comment]
@sergeysova затестил. И тут напишу D

- Не смертельная трабла

удаляя сообщения в телеге у нас в бд оно остается и в следующий раз телега вернет 404 и сколько лишних запросов будет **(мб удалять и в бд) ?**

- Смертельная 

Тут `featureBotParticipation `нету `notifySpammerAutoban` ибо откуда ему там быть ? Ты планировал футурам биндить контекст ? А так пока его там нету D
**А в общем все работает.** Я затестил ручками D. Хз как там будет с твоими тестами. Но я их жаждю. Ибо жесть. Хотя так оно позволит тестить ?

**Comment by dmitryshelomanov** [comment]
upd
`ctx.privateChannel.notifySpammerAutoban` смертельная трабла снята
просто видимо ты ночью писал D
**нужно было из контекста брать**
