### ISSUE TITLE
Оставлять "!ро причина"  в чате для устрашения других

### ISSUE THREAD

**Issue by syabro** [telegram-ru/ru-bot#76]
![heads_on_spikes](https://user-images.githubusercontent.com/29029/42705812-425d8a8c-86dd-11e8-8a64-24055537014d.png)

**Comment by Piterden** [comment]
— Если не понимаешь, что говорят, полагаю, вот это ты понимаешь.
— Довольно грубо тыкать людям оружием в спину.
— Я, как и ты, Таннен, обманываю всякий раз, когда могу.

*Назад в будущее 3 (Back to the Future 3)*
